---
- name: Add ansible control user
  when: include_ansible_control_environment
  block:
    - name: Configure group for ansible control user
      become: yes
      tags:
        - ansible_user
        - ansible_control
      group:
        gid: "{{ ansible_control_gid | int }}"
        name: "{{ ansible_control_user_name }}"
        state: present
    - name: Configure ansible control user
      become: yes
      tags:
        - ansible_user
        - ansible_control
      user:
        uid: "{{ ansible_control_uid | int }}"
        name: "{{ ansible_control_user_name }}"
        password: "{{ ansible_control_user_password }}"
        comment: "{{ ansible_control_user_comment }}"
        home: "{{ ansible_control_user_home }}"
        create_home: yes
        expires:
        group: "{{ ansible_control_user_name }}"
        groups: "{{ ansible_control_groups | union(os_family_groups) }}"
        generate_ssh_key: yes
        ssh_key_passphrase: "{{ ansible_control_ssh_passphrase }}"
        ssh_key_type: ed25519
        state: present
      notify:
        - Copy files from ansible control user dir under /home to new (if different)
    
    - name: Configure permissions on ansible control home directory
      become: yes
      tags:
       - ansible_user
       - ansible_control
       - file_dir_permissions
      file:
        path: "{{ ansible_control_user_home }}"
        state: directory
        mode: 0700
        owner: "{{ ansible_control_user_name }}"
        group: "{{ ansible_control_user_name }}"
    
    - name: Configure ownership on files/dirs in ansible control home directory
      become: yes
      tags:
       - ansible_user
       - ansible_control
       - file_dir_ownership
      file:
        path: "{{ ansible_control_user_home }}"
        state: directory
        owner: "{{ ansible_control_user_name }}"
        group: "{{ ansible_control_user_name }}"
        recurse: yes
    
    - name: Configure SSH authorized keys for ansible_control user
      become: yes
      tags:
        - ansible_control_user
        - ssh
      vars:
        ansible_control_user_public_keys:
          - public_keys/ansible_control_user
          - ~/.ssh/id_ed25519.pub
          - ~/.ssh/id_rsa.pub
      authorized_key:
        user: "{{ ansible_control_user_name }}"
        state: present
        key: "{{ lookup('file', lookup('first_found', ansible_control_user_public_keys)) }}"
        exclusive: True
