---
- name: Configure local admin user
  tags:
    - admin_user
    - ssh
  become: yes
  block:
    - name: Configure group for local admin user
      group:
        gid: "{{ admin_gid | int }}"
        name: "{{ admin_user_name }}"
        state: present

    - name: Configure local admin user
      user:
        uid: "{{ admin_uid | int }}"
        name: "{{ admin_user_name }}"
        password: "{{ admin_user_password }}"
        comment: "{{ admin_user_comment }}"
        create_home: yes
        expires:
        group: "{{ admin_user_name }}"
        groups: "{{ admin_groups | union(os_family_groups) }}"
        state: present

    - name: Configure SSH authorized keys for local admin user
      vars:
        admin_user_public_key:
          - public_keys/admin_user
          - ~/id_ed25519.pub
          - ~/id_rsa.pub
      authorized_key:
        user: "{{ admin_user_name }}"
        state: present
        key: "{{ lookup('file', lookup('first_found', admin_user_public_key)) }}"
        exclusive: True
