---
- name: Configure ansible-client user
  tags:
    - ansible
    - ansible-client
    - ssh
  become: yes
  block:
    - name: Configure group for ansible-client user
      group:
        gid: "{{ ansible_client_gid | int }}"
        name: "{{ ansible_client_user_name }}"
        state: present

    - name: Configure ansible-client user
      user:
        uid: "{{ ansible_client_uid | int }}"
        name: "{{ ansible_client_user_name }}"
        password: "{{ ansible_client_user_password }}"
        comment: "{{ ansible_client_user_comment }}"
        create_home: yes
        expires:
        group: "{{ ansible_client_user_name }}"
        groups: "{{ ansible_client_groups | union(os_family_groups) }}"
        state: present

    - name: Configure SSH authorized keys for ansible-client user
      vars:
        ansible_client_public_key:
          - "public_keys/ansible_client_user"
          - "{{ ansible_control_user_home }}/.ssh/id_ed25519.pub"
      authorized_key:
        user: "{{ ansible_client_user_name }}"
        state: present
        key: "{{ lookup('file', lookup('first_found', ansible_client_public_key)) }}"
        exclusive: True

